name: "Calculate Idris Version"
description: "Calculate idris version (vx.x.x or latest)"

inputs:
  event_name:
    required: true
    description: "The value of github.event_name"
  workflow_dispatch_version:
    required: false
    description: "The value of inputs.version from a workflow_dispatch event"

outputs:
  version:
    description: "The idris version to use"
    value: ${{ steps.idris-output.outputs.idris-version }}

runs:
  using: composite
  steps:
    - name: Idris Version Default (Non workflow dispatch/call)
      if: ${{ inputs.event_name != 'workflow_dispatch' }}
      run: echo "GITHUB_IDRIS_VERSION=latest" >> $GITHUB_ENV

    - name: Idris Version (Workflow call/dispatch)
      if: ${{ inputs.event_name == 'workflow_dispatch' }}
      run: echo "GITHUB_IDRIS_VERSION=${{ inputs.workflow_dispatch_version }}" >> $GITHUB_ENV

    # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-actions
    - name: Output
      id: idris-output
      run: echo "::set-output name=idris-version::$(echo $GITHUB_IDRIS_VERSION)"
      shell: bash
