name: Build Dockerfiles

on:
  workflow_dispatch:
    inputs:
      version:
        description: Idris Version
        required: true
        default: "v0.5.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build Dockerfile
        run: |
          echo "Building Dockerfile for Idris ${{ github.event.inputs.version }}"
          docker build -t builder --build-arg IDRIS_VERSION=${{ github.event.inputs.version }} . -f Dockerfile.builder
          docker run -it builder idris2 --version
