name: Deploy Docker Images

on:
  # manually deploy a specific
  # if version isn't specified, it will deploy nightly
  workflow_dispatch:
    inputs:
      version:
        description: Idris Version
        required: true
        default: "latest"
  push:
    paths:
      - ".github/workflows/deploy.yml" # this file
      - "devcontainer.Dockerfile"
      - ".github/actions/setup-buildx/action.yml" # deps

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  packages: write
  contents: read

jobs:
  build-single-version:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Buildx
        uses: "./.github/actions/setup-buildx"
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_ip: ${{ secrets.SSH_IP }}

      - name: Login to GHCR
        uses: docker/login-action@be010b42938448d8a286c21d5c4ccf2aae1524a1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          file: devcontainer.Dockerfile
          build-args: |
            IDRIS_VERSION=${{ inputs.version }}
          tags: ${{ steps.create-meta.outputs.tags }}
          labels: ${{ inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-deploy:
    if: ${{ github.event_name == 'push' }}
    strategy:
      matrix:
        idris-version: ["v0.3.0", "v0.4.0", "v0.5.0", "v0.5.1"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Buildx
        uses: "./.github/actions/setup-buildx"
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_ip: ${{ secrets.SSH_IP }}

      - name: Login to GHCR
        uses: docker/login-action@be010b42938448d8a286c21d5c4ccf2aae1524a1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: create-meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          file: devcontainer.Dockerfile
          build-args: |
            IDRIS_VERSION=${{ matrix.idris-version }}
          tags: ${{ steps.create-meta.outputs.tags }}
          labels: ${{ matrix.idris-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
