name: Deploy Docker Images

on:
  # manually deploy a specific
  # if version isn't specified, it will deploy nightly
  workflow_dispatch:
    inputs:
      version:
        description: Idris Version
        required: true
        default: "latest"
  push:
    paths:
      - ".github/workflows/deploy.yml" # this file
      - "devcontainer.Dockerfile"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  packages: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # to build the arm image, qemu is too slow (about 3hrs to build)
      # so we use my personal Oracle VPS as a buildx builder via ssh
      - name: 💻 Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >>~/.ssh/config <<END
          Host arm-vm
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}

      # Creating our own builder lets us have more control over the build process
      # we are making the actions runner natively build the amd image, but SSH into our arm VM for the arm image
      # https://www.docker.com/blog/speed-up-building-with-docker-buildx-and-graviton2-ec2/
      # this allows u to still use build-push-action, but docker will automatically choose which builder to use based on the platform
      - name: Setup Buildx Instances
        run: |
          docker buildx create --use --name main-builder --platform=linux/amd64 --driver=docker-container
          docker buildx create --append --name=main-builder --platform=linux/arm64 ssh://arm-vm
          docker buildx inspect main-builder --bootstrap
          docker buildx ls

      - name: Login to GHCR
        uses: docker/login-action@be010b42938448d8a286c21d5c4ccf2aae1524a1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Idris Version
        id: idris-version
        uses: ./.github/actions/get-idris-version
        with:
          event_name: ${{ github.event_name }}
          workflow_dispatch_version: ${{ inputs.version }}

      - name: Build and push
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          file: devcontainer.Dockerfile
          build-args: |
            IDRIS_VERSION=${{ steps.idris-version.outputs.version }}
          tags: ${{ steps.create-meta.outputs.tags }}
          labels: ${{ steps.idris-version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
