name: Deploy Docker Images

on:
  workflow_dispatch:
    inputs:
      version:
        description: Idris Version
        required: true
        default: "v0.5.1"
  push:
    paths:
      - ".github/workflows/deploy.yml" # this file
      - "devcontainer.Dockerfile"

permissions:
  packages: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: 💻 Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >>~/.ssh/config <<END
          Host arm-vm
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}

      - name: Test SSH connection
        run: ssh arm-vm echo "SSH connection successful"

      - name: Setup Buildx (amd64)
        id: buildx-amd
        uses: docker/setup-buildx-action@v2

      - name: Setup Buildx (arm64 SSH)
        run: |
          docker buildx create --name buildx-arm --driver docker-container --platform linux/arm64 ssh://arm-vm
          docker buildx inspect --bootstrap --builder buildx-arm

      - name: Check Buildx Builders
        run: docker buildx ls

      - name: Setup Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: create-meta
        uses: docker/metadata-action@v4
        with:
          images: joshuanianji/idris2

      # If we are not doing a workflow dispatch/call, we have to manually set the idris version
      - name: Set Environment (Non workflow dispatch/call)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: echo "GITHUB_IDRIS_VERSION=v0.5.1" >> $GITHUB_ENV

      - name: Set Environment (Workflow call/dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "GITHUB_IDRIS_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Test Environment
        run: echo $GITHUB_IDRIS_VERSION

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          # push: ${{ github.event_name != 'pull_request' }}
          file: devcontainer.Dockerfile
          build-args: |
            IDRIS_VERSION=${{ env.GITHUB_IDRIS_VERSION }}
          push: false
          tags: ${{ steps.create-meta.outputs.tags }}
          labels: ${{ steps.create-meta.outputs.labels }}
