name: Deploy Docker Images

on:
  # manually deploy a specific
  # if version isn't specified, it will deploy nightly
  workflow_dispatch:
    inputs:
      version:
        description: Idris Version
        required: false
        default: "v0.5.1"
  push:
    paths:
      - ".github/workflows/deploy.yml" # this file
      - "devcontainer.Dockerfile"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  packages: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # to build the arm image, qemu is too slow (about 3hrs to build)
      # so we use my personal Oracle VPS as a buildx builder via ssh
      - name: 💻 Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >>~/.ssh/config <<END
          Host arm-vm
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}

      - name: Setup Buildx Instances
        run: |
          docker buildx create --use --name main-builder --platform=linux/amd64 --driver=docker-container
          docker buildx create --append --name=main-builder --platform=linux/arm64 ssh://arm-vm
          docker buildx inspect main-builder --bootstrap
          docker buildx ls

      - name: Login to GHCR
        uses: docker/login-action@be010b42938448d8a286c21d5c4ccf2aae1524a1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # If we are not doing a workflow dispatch/call, we have to manually set the idris version
      - name: Set Environment (Non workflow dispatch/call)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: echo "GITHUB_IDRIS_VERSION=v0.5.1" >> $GITHUB_ENV

      - name: Set Environment (Workflow call/dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "GITHUB_IDRIS_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Test Environment
        run: echo $GITHUB_IDRIS_VERSION

      - name: Build and push
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          file: devcontainer.Dockerfile
          build-args: |
            IDRIS_VERSION=${{ env.GITHUB_IDRIS_VERSION }}
          tags: ${{ steps.create-meta.outputs.tags }}
          labels: ${{ steps.create-meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
