name: Deploy Docker Images

on:
  # manually deploy a specific
  # if version isn't specified, it will deploy nightly
  workflow_dispatch:
    inputs:
      version:
        description: Idris Version
        required: true
        default: "latest"
  push:
    paths:
      - ".github/workflows/deploy.yml" # this file
      - "*.Dockerfile"
      # single
      - ".github/actions/setup-buildx/action.yml"
      - ".github/workflows/build-and-deploy-single.yml"

permissions:
  packages: write
  contents: read

jobs:
  base-single:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/build-and-deploy-single.yml
    with:
      version: ${{ inputs.version }}
      dockerfile: base.Dockerfile
      image-name: ${{ github.repository }}/base
    secrets: inherit

  base-matrix:
    if: ${{ github.event_name == 'push' }}
    strategy:
      matrix:
        idris-version: ["v0.5.0", "v0.5.1", "latest"]
    uses: ./.github/workflows/build-and-deploy-single.yml
    with:
      version: ${{ matrix.idris-version }}
      dockerfile: base.Dockerfile
      image-name: ${{ github.repository }}/base
    secrets: inherit
